# Generated by Django 4.1.6 on 2023-03-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('SN', 'Sneakers'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default='SN', max_length=2, null=True),
        ),
    ]
