# Generated by Django 4.1.6 on 2023-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'Brand')], default='SN', max_length=2, null=True),
        ),
    ]
