# Generated by Django 4.1.6 on 2023-03-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_parent_category_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(default='DD1391-100', max_length=100),
        ),
    ]
