# Generated by Django 4.1.6 on 2023-03-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_released',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(max_length=100),
        ),
    ]
