# Generated by Django 4.1.6 on 2023-03-19 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_rename_sku_product_sku_alter_product_year_released'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variationoption',
            unique_together=set(),
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Vendor',
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productitem')),
                ('variation_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variationoption')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='variationoption',
            name='item_variations',
        ),
    ]
