# Generated by Django 4.1.6 on 2023-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_variationoption_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationoption',
            old_name='value',
            new_name='eu',
        ),
        migrations.AddField(
            model_name='variationoption',
            name='ru',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationoption',
            name='uk',
            field=models.CharField(default='fd', max_length=50),
            preserve_default=False,
        ),
    ]
