# Generated by Django 4.1.6 on 2023-03-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_value_variationoption_eu_variationoption_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfiguration',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='user',
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
