# Generated by Django 4.1.6 on 2023-03-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_productconfiguration_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productconfiguration',
            name='product_item',
        ),
        migrations.AddField(
            model_name='product',
            name='qty_in_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
