# Generated by Django 4.1.6 on 2023-04-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_productconfiguration_product_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationoption',
            old_name='eu',
            new_name='eu_size',
        ),
        migrations.RenameField(
            model_name='variationoption',
            old_name='ru',
            new_name='ru_size',
        ),
        migrations.RenameField(
            model_name='variationoption',
            old_name='uk',
            new_name='uk_size',
        ),
    ]
